package com.lusiwei.house.ds.dao;

import java.util.List;
import com.lusiwei.house.common.pojo.Agency;

public interface AgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency
     *
     * @mbg.generated
     */
    int insert(Agency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency
     *
     * @mbg.generated
     */
    Agency selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency
     *
     * @mbg.generated
     */
    List<Agency> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Agency record);
}