package com.lusiwei.house.ds.dao;

import java.util.List;
import com.lusiwei.house.common.pojo.HouseMsg;

public interface HouseMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated
     */
    int insert(HouseMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated
     */
    HouseMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated
     */
    List<HouseMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HouseMsg record);
}