package com.lusiwei.house.ds.dao;

import java.util.List;
import com.lusiwei.house.common.pojo.HouseUser;

public interface HouseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated
     */
    int insert(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated
     */
    HouseUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated
     */
    List<HouseUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HouseUser record);
}