package com.lusiwei.house.ds.dao;

import com.lusiwei.house.common.pojo.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    int selectByUserName(String name);

    int selectByPhone(String phone);

    int selectByEmail(String email);

    void deleteUserByEmail(String email);

    User selectByEmailAndPassword(@Param("email") String username, @Param("password") String password);

    void updateStatus(String email);
}