package com.lusiwei.house.common.pojo;

public class Agency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.about_us
     *
     * @mbg.generated
     */
    private String aboutUs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency.web_site
     *
     * @mbg.generated
     */
    private String webSite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.id
     *
     * @return the value of agency.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.id
     *
     * @param id the value for agency.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.name
     *
     * @return the value of agency.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.name
     *
     * @param name the value for agency.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.address
     *
     * @return the value of agency.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.address
     *
     * @param address the value for agency.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.phone
     *
     * @return the value of agency.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.phone
     *
     * @param phone the value for agency.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.email
     *
     * @return the value of agency.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.email
     *
     * @param email the value for agency.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.about_us
     *
     * @return the value of agency.about_us
     *
     * @mbg.generated
     */
    public String getAboutUs() {
        return aboutUs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.about_us
     *
     * @param aboutUs the value for agency.about_us
     *
     * @mbg.generated
     */
    public void setAboutUs(String aboutUs) {
        this.aboutUs = aboutUs == null ? null : aboutUs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.mobile
     *
     * @return the value of agency.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.mobile
     *
     * @param mobile the value for agency.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency.web_site
     *
     * @return the value of agency.web_site
     *
     * @mbg.generated
     */
    public String getWebSite() {
        return webSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency.web_site
     *
     * @param webSite the value for agency.web_site
     *
     * @mbg.generated
     */
    public void setWebSite(String webSite) {
        this.webSite = webSite == null ? null : webSite.trim();
    }
}